version: "3.9"

services:
  hello1:
    build: 
      context: .
      dockerfile: Dockerfile   
    command: node hello-1
    environment:
      port: 6379
      NODE_ENV: prod    
      host: redis
    ports:
      - "8000"
  hello2:
    build: 
      context: .
      dockerfile: Dockerfile
    command: node hello-2 
    environment:
      PORT: 8000
      NODE_ENV: dev 
    ports:
      - "8000"
  nginx-proxy:
    build: ./nginx
    depends_on:
      - hello1
      - hello2
    image: nginx:alpine
    ports:
      - "80:80"
  redis:
    image: "redis:latest"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]    
